export type FoilMotifType =
  | 'constellation'
  | 'abstract geometric'
  | 'botanical foliage'
  | 'radial sunburst'
  | 'minimalist serif initials';

export type FoilColor = 'gold' | 'silver' | 'rosegold' | 'copper';

export interface ShelfBookManifestItem {
  id: string;
  title: string;
  author: string;
  coverUrl?: string;
  year: number;
  genre: string;
  pages: number;
  tagline: string;
  description: string;
  height: number;      // 2.2 - 3.4
  width: number;       // 1.4 - 2.2
  thickness: number;   // 0.25 - 0.75
  clothColor: string;  // Hex color
  clothName: string;
  foilColor: FoilColor;
  foilHex: string;
  foilMotif: FoilMotifType;
}

export const CLOTH_PALETTE = {
  deepNavy: '#162238',
  burgundy: '#521422',
  emerald: '#163E2D',
  warmCharcoal: '#282726',
  terracotta: '#9E442A',
  forest: '#183324',
  ochre: '#A36F17',
  cream: '#F4F0E8',
} as const;

export const FOIL_PALETTE: Record<FoilColor, string> = {
  gold: '#F3D274',
  silver: '#E2E8F0',
  rosegold: '#F0A899',
  copper: '#E07A5F',
};

export const MINT_BOOK_MANIFEST: ShelfBookManifestItem[] = [
  {
    id: 'book-1',
    title: 'The Odyssey',
    author: 'Homer',
    year: -700,
    genre: 'Epic Poetry',
    pages: 448,
    tagline: 'Sing in me, Muse, and through me tell the story',
    description: 'An enduring epic of Odysseus, ten years wandering home after the fall of Troy, encountering mythical monsters and gods.',
    height: 3.2,
    width: 2.1,
    thickness: 0.65,
    clothColor: CLOTH_PALETTE.deepNavy,
    clothName: 'Deep Navy Cloth',
    foilColor: 'gold',
    foilHex: FOIL_PALETTE.gold,
    foilMotif: 'constellation',
  },
  {
    id: 'book-2',
    title: 'Faust',
    author: 'Johann Wolfgang von Goethe',
    year: 1808,
    genre: 'Dramatic Tragedy',
    pages: 464,
    tagline: 'Two souls alas! dwell in my breast together',
    description: 'A tragic play depicting the scholar Faust making a pact with Mephistopheles in pursuit of infinite wisdom.',
    height: 2.9,
    width: 1.9,
    thickness: 0.55,
    clothColor: CLOTH_PALETTE.burgundy,
    clothName: 'Royal Burgundy Cloth',
    foilColor: 'gold',
    foilHex: FOIL_PALETTE.gold,
    foilMotif: 'radial sunburst',
  },
  {
    id: 'book-3',
    title: 'Walden',
    author: 'Henry David Thoreau',
    year: 1854,
    genre: 'Philosophy / Nature',
    pages: 352,
    tagline: 'I went to the woods because I wished to live deliberately',
    description: 'A reflection upon simple living in natural surroundings and transcendental contemplation at Walden Pond.',
    height: 2.7,
    width: 1.75,
    thickness: 0.45,
    clothColor: CLOTH_PALETTE.forest,
    clothName: 'Deep Forest Green Cloth',
    foilColor: 'rosegold',
    foilHex: FOIL_PALETTE.rosegold,
    foilMotif: 'botanical foliage',
  },
  {
    id: 'book-4',
    title: 'Meditations',
    author: 'Marcus Aurelius',
    year: 180,
    genre: 'Stoic Philosophy',
    pages: 256,
    tagline: 'You have power over your mind - not outside events',
    description: 'Private journal entries of the Roman Emperor reflecting on stoicism, duty, mortality, and personal virtue.',
    height: 2.5,
    width: 1.6,
    thickness: 0.35,
    clothColor: CLOTH_PALETTE.warmCharcoal,
    clothName: 'Warm Charcoal Linen',
    foilColor: 'gold',
    foilHex: FOIL_PALETTE.gold,
    foilMotif: 'minimalist serif initials',
  },
  {
    id: 'book-5',
    title: 'Divine Comedy',
    author: 'Dante Alighieri',
    year: 1320,
    genre: 'Epic Poetry',
    pages: 798,
    tagline: 'Abandon all hope, ye who enter here',
    description: 'Dante’s journey through Inferno, Purgatorio, and Paradiso guided by the Roman poet Virgil and Beatrice.',
    height: 3.4,
    width: 2.2,
    thickness: 0.75,
    clothColor: CLOTH_PALETTE.terracotta,
    clothName: 'Tuscan Terracotta Cloth',
    foilColor: 'copper',
    foilHex: FOIL_PALETTE.copper,
    foilMotif: 'radial sunburst',
  },
  {
    id: 'book-6',
    title: 'Principia Mathematica',
    author: 'Sir Isaac Newton',
    year: 1687,
    genre: 'Natural Philosophy',
    pages: 560,
    tagline: 'Mathematical Principles of Natural Philosophy',
    description: 'Foundational work establishing the laws of motion, universal gravitation, and mathematical physics.',
    height: 3.3,
    width: 2.15,
    thickness: 0.7,
    clothColor: CLOTH_PALETTE.ochre,
    clothName: 'Antique Ochre Buckram',
    foilColor: 'gold',
    foilHex: FOIL_PALETTE.gold,
    foilMotif: 'abstract geometric',
  },
  {
    id: 'book-7',
    title: 'The Art of War',
    author: 'Sun Tzu',
    year: -450,
    genre: 'Military Strategy',
    pages: 192,
    tagline: 'In the midst of chaos, there is also opportunity',
    description: 'An ancient Chinese military treatise attributed to Sun Tzu, detailing tactical mastery and strategic wisdom.',
    height: 2.3,
    width: 1.5,
    thickness: 0.28,
    clothColor: CLOTH_PALETTE.emerald,
    clothName: 'Imperial Emerald Cloth',
    foilColor: 'silver',
    foilHex: FOIL_PALETTE.silver,
    foilMotif: 'minimalist serif initials',
  },
  {
    id: 'book-8',
    title: 'Leaves of Grass',
    author: 'Walt Whitman',
    year: 1855,
    genre: 'Poetry',
    pages: 440,
    tagline: 'I celebrate myself, and sing myself',
    description: 'A milestone poetry collection celebrating humanity, nature, democracy, and transcendentalism.',
    height: 2.8,
    width: 1.85,
    thickness: 0.52,
    clothColor: CLOTH_PALETTE.cream,
    clothName: 'Natural Cream Linen',
    foilColor: 'gold',
    foilHex: FOIL_PALETTE.gold,
    foilMotif: 'botanical foliage',
  },
  {
    id: 'book-9',
    title: 'The Republic',
    author: 'Plato',
    year: -375,
    genre: 'Political Philosophy',
    pages: 416,
    tagline: 'Justice in the soul and the ideal city state',
    description: 'Socratic dialogue discussing justice, the order and character of the just city-state, and the philosopher king.',
    height: 3.0,
    width: 1.95,
    thickness: 0.58,
    clothColor: CLOTH_PALETTE.deepNavy,
    clothName: 'Deep Navy Cloth',
    foilColor: 'silver',
    foilHex: FOIL_PALETTE.silver,
    foilMotif: 'abstract geometric',
  },
  {
    id: 'book-10',
    title: 'Paradise Lost',
    author: 'John Milton',
    year: 1667,
    genre: 'Epic Poetry',
    pages: 480,
    tagline: 'Better to reign in Hell than serve in Heaven',
    description: 'An epic poem in blank verse concerning the biblical story of the Fall of Man and the temptation of Adam and Eve.',
    height: 3.1,
    width: 2.0,
    thickness: 0.62,
    clothColor: CLOTH_PALETTE.burgundy,
    clothName: 'Royal Burgundy Cloth',
    foilColor: 'gold',
    foilHex: FOIL_PALETTE.gold,
    foilMotif: 'constellation',
  },
  {
    id: 'book-11',
    title: 'Critique of Pure Reason',
    author: 'Immanuel Kant',
    year: 1781,
    genre: 'Epistemology',
    pages: 720,
    tagline: 'Thoughts without content are empty, intuitions without concepts are blind',
    description: 'A landmark treatise examining the bounds and scope of human knowledge and transcendental idealism.',
    height: 3.25,
    width: 2.1,
    thickness: 0.72,
    clothColor: CLOTH_PALETTE.warmCharcoal,
    clothName: 'Warm Charcoal Linen',
    foilColor: 'silver',
    foilHex: FOIL_PALETTE.silver,
    foilMotif: 'abstract geometric',
  },
  {
    id: 'book-12',
    title: 'The Metamorphosis',
    author: 'Franz Kafka',
    year: 1915,
    genre: 'Modernist Novella',
    pages: 128,
    tagline: 'One morning, Gregor Samsa awoke from troubling dreams...',
    description: 'The story of salesman Gregor Samsa, who wakes one morning to find himself transformed into a monstrous insect.',
    height: 2.2,
    width: 1.4,
    thickness: 0.25,
    clothColor: CLOTH_PALETTE.terracotta,
    clothName: 'Tuscan Terracotta Cloth',
    foilColor: 'copper',
    foilHex: FOIL_PALETTE.copper,
    foilMotif: 'minimalist serif initials',
  },
  {
    id: 'book-13',
    title: 'Ethica',
    author: 'Baruch Spinoza',
    year: 1677,
    genre: 'Metaphysics',
    pages: 320,
    tagline: 'Demonstrated in Geometrical Order',
    description: 'A philosophical masterpiece asserting that God and Nature are one unified substance expressed through infinity.',
    height: 2.85,
    width: 1.8,
    thickness: 0.48,
    clothColor: CLOTH_PALETTE.emerald,
    clothName: 'Imperial Emerald Cloth',
    foilColor: 'gold',
    foilHex: FOIL_PALETTE.gold,
    foilMotif: 'constellation',
  },
  {
    id: 'book-14',
    title: 'The Origin of Species',
    author: 'Charles Darwin',
    year: 1859,
    genre: 'Evolutionary Biology',
    pages: 502,
    tagline: 'There is grandeur in this view of life',
    description: 'A seminal work of scientific literature introducing the theory of evolution by natural selection.',
    height: 3.15,
    width: 2.05,
    thickness: 0.68,
    clothColor: CLOTH_PALETTE.forest,
    clothName: 'Deep Forest Green Cloth',
    foilColor: 'rosegold',
    foilHex: FOIL_PALETTE.rosegold,
    foilMotif: 'botanical foliage',
  },
  {
    id: 'book-15',
    title: 'Thus Spoke Zarathustra',
    author: 'Friedrich Nietzsche',
    year: 1883,
    genre: 'Philosophical Fiction',
    pages: 350,
    tagline: 'Man is something that shall be overcome',
    description: 'A philosophical novel expounding the ideas of the Übermensch, the will to power, and the eternal recurrence.',
    height: 2.75,
    width: 1.78,
    thickness: 0.5,
    clothColor: CLOTH_PALETTE.ochre,
    clothName: 'Antique Ochre Buckram',
    foilColor: 'gold',
    foilHex: FOIL_PALETTE.gold,
    foilMotif: 'radial sunburst',
  },
  {
    id: 'book-16',
    title: 'The Book of Disquiet',
    author: 'Fernando Pessoa',
    year: 1982,
    genre: 'Modernist Fragments',
    pages: 544,
    tagline: 'My soul is a hidden orchestra',
    description: 'A breathtaking masterpiece composed of lyrical fragments, introspection, and existential poetry by Bernardo Soares.',
    height: 3.0,
    width: 1.9,
    thickness: 0.64,
    clothColor: CLOTH_PALETTE.deepNavy,
    clothName: 'Deep Navy Cloth',
    foilColor: 'rosegold',
    foilHex: FOIL_PALETTE.rosegold,
    foilMotif: 'minimalist serif initials',
  },
  {
    id: 'book-17',
    title: 'Selected Sonnets',
    author: 'William Shakespeare',
    year: 1609,
    genre: 'Poetry',
    pages: 224,
    tagline: 'Shall I compare thee to a summer’s day?',
    description: 'A timeless collection of 154 sonnets dealing with themes of love, beauty, mortality, and passage of time.',
    height: 2.4,
    width: 1.55,
    thickness: 0.32,
    clothColor: CLOTH_PALETTE.burgundy,
    clothName: 'Royal Burgundy Cloth',
    foilColor: 'gold',
    foilHex: FOIL_PALETTE.gold,
    foilMotif: 'botanical foliage',
  },
  {
    id: 'book-18',
    title: 'Principles of Psychology',
    author: 'William James',
    year: 1890,
    genre: 'Psychology',
    pages: 680,
    tagline: 'The stream of consciousness',
    description: 'A monumental foundational text exploring emotion, habit, attention, perception, and stream of consciousness.',
    height: 3.3,
    width: 2.1,
    thickness: 0.74,
    clothColor: CLOTH_PALETTE.cream,
    clothName: 'Natural Cream Linen',
    foilColor: 'copper',
    foilHex: FOIL_PALETTE.copper,
    foilMotif: 'abstract geometric',
  },
  {
    id: 'book-19',
    title: 'Cosmos & Microcosmos',
    author: 'Alexander von Humboldt',
    year: 1845,
    genre: 'Natural Science',
    pages: 610,
    tagline: 'Nature is a net of interwoven forces',
    description: 'A comprehensive physical description of the universe, integrating geography, astronomy, botany, and humanities.',
    height: 3.2,
    width: 2.05,
    thickness: 0.66,
    clothColor: CLOTH_PALETTE.ochre,
    clothName: 'Antique Ochre Buckram',
    foilColor: 'gold',
    foilHex: FOIL_PALETTE.gold,
    foilMotif: 'constellation',
  },
];
