import { subjectLabel } from './formatters';
import type { ManualBlock, SubjectKey } from './types';

const SUBJECT_PATTERNS: Array<{ subject: SubjectKey; patterns: RegExp[] }> = [
  {
    subject: 'portugues',
    patterns: [
      /^PT\b/i,
      /portugu[eê]s/i,
      /reda[cç][aã]o/i,
      /sintaxe/i,
      /concord[aâ]ncia/i,
      /reg[eê]ncia/i,
      /crase/i,
      /pontua[cç][aã]o/i,
      /interpreta[cç][aã]o/i,
      /coes[aã]o/i,
      /reescrita/i,
      /ora[cç][oõ]es/i,
    ],
  },
  { subject: 'rlm', patterns: [/^RLM\b/i, /racioc[ií]nio/i, /matem[aá]tica/i] },
  {
    subject: 'legislacao',
    patterns: [
      /^Legis\b/i,
      /lei\b/i,
      /regimento/i,
      /legisla/i,
      /lc\s*\d+/i,
      /constitui[cç][aã]o/i,
      /improbidade/i,
      /administra[cç][aã]o p[uú]blica/i,
      /estatuto/i,
      /org[aâ]nica/i,
    ],
  },
  {
    subject: 'especificos',
    patterns: [
      /^TI\b/i,
      /java/i,
      /web/i,
      /banco/i,
      /redes/i,
      /seguran[cç]a/i,
      /itil/i,
      /cobit/i,
      /pmbok/i,
      /bpmn/i,
      /bpm\b/i,
      /iso/i,
      /owasp/i,
      /lgpd/i,
      /lai\b/i,
      /marco civil/i,
      /scrum/i,
      /[aá]gil/i,
      /kanban/i,
      /lean/i,
      /xp\b/i,
      /apf\b/i,
      /uml/i,
      /devops/i,
      /ci\/cd/i,
      /solid/i,
      /clean architecture/i,
      /togaf/i,
      /rest\b/i,
      /soap\b/i,
      /oauth/i,
      /saml/i,
      /openid/i,
      /sso/i,
      /rbac/i,
      /sql/i,
      /postgresql/i,
      /nosql/i,
      /data warehouse/i,
      /etl/i,
      /big data/i,
      /aprendizado/i,
      /ia\b/i,
      /intelig[eê]ncia/i,
      /tcp\/ip/i,
      /osi/i,
      /nuvem/i,
      /iaas/i,
      /paas/i,
      /saas/i,
      /faas/i,
      /docker/i,
      /kubernetes/i,
      /active directory/i,
      /ldap/i,
      /backup/i,
      /disaster recovery/i,
      /criptografia/i,
      /testes/i,
      /sast/i,
      /dast/i,
      /samm/i,
      /bsimm/i,
    ],
  },
];

export const inferManualBlockSubject = (block: ManualBlock): SubjectKey | null => {
  const haystack = `${block.area} ${block.title} ${block.detail}`;
  const match = SUBJECT_PATTERNS.find(({ patterns }) => patterns.some((pattern) => pattern.test(haystack)));
  return match?.subject ?? null;
};

export const getManualBlockSubjectLabel = (block: ManualBlock): string => {
  const subject = inferManualBlockSubject(block);
  return subject ? subjectLabel(subject) : block.area;
};
